---
- hosts: appmwmq01d:appmwmq02d
  become: yes
  serial: 1
  vars:
   - QMGR:
       - DASDB
       - AUDIT
       - SAU_PROD
       - PUSH
       - APP_DAS
       - TYPEB
  tasks:
   - name: check NFS status
     wait_for:
       host: appmnfs01d
       port: 2049
       timeout: 5
     register: nfs_status
     when: inventory_hostname  in ["appmwmq01d","appmwmq02d"]
   - name: check /mqshare
     stat:
      path: /mqshare/qmgr/AUDIT
     register: mount_point
     when: inventory_hostname  in ["appmwmq01d","appmwmq02d"]
   - block:
      - name : check dasdb QMGR STATUS
        shell: |
              /opt/mqm/bin/dspmq -m DASDB |awk '{print $(NF)}'|awk  '{print $1}' 2> /dev/null
        register: dasdb
      - set_fact:
        #msg: "{{app.results.stdout| regex_search('\\((.*?)\\)','\\1') }}"
        dasdb_status: "{{ dasdb.stdout_lines[0] |join('')|replace(')','')|replace('(','') }}"
      - name : check TYPEB QMGR STATUS
        shell: |
              /opt/mqm/bin/dspmq -m TYPEB |awk '{print $(NF)}'|awk  '{print $1}' 2> /dev/null
        register: typeb
      - set_fact:
        #msg: "{{app.results.stdout| regex_search('\\((.*?)\\)','\\1') }}"
        typeb_status: "{{ typeb.stdout_lines[0] |join('')|replace(')','')|replace('(','')}}"
      - name : check AUDIT QMGR STATUS
        shell: |
              /opt/mqm/bin/dspmq -m AUDIT |awk '{print $(NF)}'|awk  '{print $1}' 2> /dev/null
        register: audit
      - set_fact:
        #msg: "{{app.results.stdout| regex_search('\\((.*?)\\)','\\1') }}"
        audit_status: "{{ audit.stdout_lines[0] |join('')|replace(')','')|replace('(','')}}"
      - name : check APP QMGR STATUS
        shell: |
              /opt/mqm/bin/dspmq -m APP |awk '{print $(NF)}'|awk  '{print $1}' 2> /dev/null
        register: sauprod
      - debug:
          var: sauprod
      - set_fact:
        #msg: "{{app.results.stdout| regex_search('\\((.*?)\\)','\\1') }}"
        sau_prod_status: "{{ sauprod.stdout_lines[0] |join('')|replace(')','')|replace('(','')}}"
      - name : check APP_DAS QMGR STATUS
        shell: |
              /opt/mqm/bin/dspmq -m APP_DAS |awk '{print $(NF)}'|awk  '{print $1}' 2> /dev/null
        register: app_das
      - set_fact:
        #msg: "{{app.results.stdout| regex_search('\\((.*?)\\)','\\1') }}"
        app_das_status: "{{ app_das.stdout_lines[0] |join('')|replace(')','')|replace('(','')}}"
      - name : check DAS_IRISK QMGR STATUS
        shell: |
              /opt/mqm/bin/dspmq -m DAS_IRISK |awk '{print $(NF)}'|awk  '{print $1}' 2> /dev/null
        register: das_irisk
      - set_fact:
        #msg: "{{app.results.stdout| regex_search('\\((.*?)\\)','\\1') }}"
        das_irisk_status: "{{ das_irisk.stdout_lines[0] |join('')|replace(')','')|replace('(','')}}"
     when:
      - inventory_hostname  in ["appmwmq01d","appmwmq02d"] and mount_point.stat.exists
     become: yes
   - block:
        - name:  stop DASDB QMGR
          shell: |
                sudo -u mqm /opt/mqm/bin/endmqm -i DASDB |awk '{print $(NF)}'|awk  '{print $1}' 2> /dev/null 
        - name:  stop TYPEB QMGR
          shell: |
                sudo -u mqm /opt/mqm/bin/endmqm -i TYPEB |awk '{print $(NF)}'|awk  '{print $1}' 2> /dev/null
        - debug:
          var: typeb_status
        - name:  stop AUDIT QMGR
          shell: |
                sudo -u mqm /opt/mqm/bin/endmqm -i AUDIT |awk '{print $(NF)}'|awk  '{print $1}' 2> /dev/null
        - debug:
          var: audit_status
        - name:  stop APP_DAS QMGR
          shell: |
                sudo -u mqm /opt/mqm/bin/endmqm -i APP_DAS |awk '{print $(NF)}'|awk  '{print $1}' 2> /dev/null
        - debug:
          var: audit_status
        - name:  stop APP QMGR
          shell: |
                sudo -u mqm /opt/mqm/bin/endmqm -i APP |awk '{print $(NF)}'|awk  '{print $1}' 2> /dev/null
        - debug:
          var: sau_prod_status
        - name:  stop DAS_IRISK QMGR
          shell: |
                sudo -u mqm /opt/mqm/bin/endmqm -i DAS_IRISK |awk '{print $(NF)}'|awk  '{print $1}' 2> /dev/null
     when: 
        - ( das_irisk_status == 'STATUSRunning' or das_irisk_status == 'standby')
        - ( app_das_status == 'STATUSRunning' or app_das_status == 'standby')
        - ( sau_prod_status == 'STATUSRunning' or sau_prod_status == 'standby')
        - ( audit_status == 'STATUSRunning' or audit_status == 'standby')
        - ( typeb_status == 'STATUSRunning' or typeb_status == 'standby')
        - ( dasdb_status == 'STATUSRunning' or dasdb_status == 'standby')     
     register: hmm

