apiVersion: v1
kind: Secret
metadata:
  namespace: token-app
  name: app-secret-config
type: Opaque
stringData:
  secret.json: |
    {
      "company": [
        {
          "demo": "dGhpc0lzQVNlY3JldEtleUZvckRlbW9Qcm9qZWN0T25seTEyMw=="
        },
        {
          "registered": "YW5vdGhlclNlY3JldEtleUZvclJlZ2lzdGVyZWRQcm9qZWN0NDU2"
        }
      ]
    }
