apiVersion: v1
kind: ConfigMap
metadata:
  namespace: token-app
  name: token-generator-config
  labels:
    app: token-generator
data:
  application.properties: |
    # Application Server Configuration
    spring.application.name=API-TOKEN-GENERATOR
    server.port=9090
    ## Added ratelimit para
    demo.attempt=10
    regsitred.attempt=1000
    ## Added project secret 
    secret.json.path=file:/etc/myapp/json.secret/secret.json
    # Spring Data Redis Configuration
    spring.data.redis.host=redis
    spring.data.redis.port=6379
    spring.data.redis.timeout=6000ms

    # JPA / Hibernate Configuration
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

    # Active Directory / LDAP Configuration
    ad.domain=salimonline.in
    ad.url=ldap://192.168.8.142:389
    ad.root-dn=DC=salimonline,DC=in

    # JWT Security Configuration
    jwt.secret=hhZAf4BqK4KEMnFI+mLQ8LZC6MsW0temws5oVxoBckA=

    # Logging Configuration
    logging.level.root=INFO
    logging.level.org.springframework.security=DEBUG
    logging.level.oracle.salimonline.learndb=DEBUG
    logging.level.org.hibernate.orm.jdbc.bind=TRACE
